site_name: Stratasan Engineering Manual
pages:
    - Home: index.md
    - Stratasan Core Values: core_values.md
    - Engineering Values: engineering_core_values.md
    - Anti-Patterns: engineering_anti_patterns.md
    - Communication: how_we_communicate.md
    - Project Management: github.md
theme: material
