on: push
name: Deploy

push:
  branches:
  - master

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      uses: docker://python:3.6-alpine
      with:
        entrypoint: ./.github/action_runner.sh
        args: '"pip install -r requirements.txt" "mkdocs build --clean"'
    - name: deploy
      uses: actions/aws/cli@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: s3 sync ./site s3://engineering.stratasan.com/ --acl public-read --cache-control
          "public, max-age=86400"
