on:
  push:
    branches:
    - master

name: Deploy

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.x'
    - name: build site
      run: |
        pip install -r requirements.txt
        mkdocs build --clean
    - name: deploy
      run: |
        aws s3 sync ./site s3://engineering.stratasan.com/ --acl public-read --cache-control "public,max-age=86400"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
