on: push
name: CI/CD
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: build
      uses: docker://python:3.7-alpine
      with:
        entrypoint: ./.github/action_runner.sh
        args: '"pip install -r requirements.txt" "mkdocs build --clean"'
