on: push
name: CI/CD
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.x'
    - name: build site
      run: |
       pip install -r requirements.txt
       mkdocs build --clean
